name: upload_artifact

on:
  push:
    tags:
      - "v*"

jobs:
  upload_artifact:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ">=1.23.0"

      - name: Build
        run: |
          echo 'Build linux amd 64'
          env CGO_GOOS=linux GOARCH=amd64 go build
          chmod +x ./deployment-triggerer

          echo 'Build linux arm 64'
          env GOOS=linux GOARCH=arm64 go build -o deployment-triggerer-arm64
          chmod +x ./deployment-triggerer-arm64

          echo 'Build mac apple silicon'
          env GOOS=darwin GOARCH=arm64 go build -o deployment-triggerer-apple-silicon
          chmod +x ./deployment-triggerer-apple-silicon

      - name: Set GitHub user
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Publish GitHub Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "deployment-triggerer*"
          allowUpdates: true
          omitBody: true
          omitBodyDuringUpdate: true
          omitName: true
          omitNameDuringUpdate: true
